### ISSUE TITLE
val is not a non-empty string or a valid number. val=null

### ISSUE THREAD

**Issue by LarryEitel** [denrion/node-fastify-mongoose-js-template#4]
With the following env:
`# CREATE .env, .env.dev, .env.test FILES BEFORE STARTING THE SERVER
# ACCORDING TO YOUR REQUIREMENTS

# APP ENVINRONMENTS
NODE_ENV=development
PORT=3000
HOST=localhost
HOST_NAME=localhost

# FASTIFY
FASTIFY_BODY_SIZE_LIMIT=2048
FASTIFY_MAX_PARAM_LENGTH=796

# RATE LIMITING - 1h = 60*60*1000 in ms
FASTIFY_RATE_LIMIT_MAX_NUM_CONNECTIONS=100
FASTIFY_RATE_LIMIT_TIME_WINDOW_MS=1h

# MONGODB ATLAS
MONGO_DB_ATLAS_URI=localhost:27017

# JWT
JWT_SECRET=asdfasdf
JWT_EXPIRES_IN=30
JWT_COOKIE_EXPIRES_IN=30
JWT_COOKIE_NAME=larry
JWT_COOKIE_PATH=./`

I am getting:

`[nodemon] starting `node ./src/server.js`
[1606218657696] ERROR    (11492 on asus): val is not a non-empty string or a valid number. val=null
    Error: val is not a non-empty string or a valid number. val=null
        at module.exports (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\ms\index.js:34:9)
        at buildRouteRate (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastify-rate-limit\index.js:112:17)
        at Object.<anonymous> (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastify-rate-limit\index.js:95:7)
        at Object.afterRouteAdded (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastify\lib\route.js:200:16)
        at C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastify\lib\route.js:173:25
        at Object._encapsulateThreeParam (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\boot.js:545:7)
        at Boot.timeoutCall (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\boot.js:447:5)
        at Boot.callWithCbOrNextTick (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\boot.js:428:19)
        at Boot._after (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\boot.js:273:26)
        at Plugin.exec (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:131:17)
        at Boot.loadPlugin (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:266:10)
        at release (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastq\queue.js:143:16)
        at Object.resume (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastq\queue.js:76:7)
        at Plugin.finish (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:245:10)
        at C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:267:12
        at done (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:114:5)
        at fastifyCors (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastify-cors\index.js:156:3)
        at Plugin.exec (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:131:17)
        at Boot.loadPlugin (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:266:10)
        at Task.release (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastq\queue.js:143:16)
        at worked (C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\fastq\queue.js:195:10)
        at C:\Users\Larry\Documents\GitHub\node-fastify-mongoose-js-template\node_modules\avvio\plugin.js:269:7`

Perhaps you can consider populating your sample config with example values?

Thank you for sharing this repo.

**Comment by denrion** [comment]
Hey @LarryEitel ,

The problem occurs because of this line: 
`FASTIFY_RATE_LIMIT_TIME_WINDOW_MS=1h`

Change it to this and it should work: 
`FASTIFY_RATE_LIMIT_TIME_WINDOW_MS=3600000`

This repo was made primarily for my personal use, therefore documentation is lacking a bit unfortunately. But feel free to keep using it and let me know if any more problems pop up :) 

I'll update the repo with examples as you suggested.
